### ISSUE TITLE
Localhost perf testing

### ISSUE THREAD

**Issue by TheAngryByrd** [Krzysztof-Cieslak/Suave.Kestrel#1]
Take with lots of salt since this is a localhost test.

Cores: 4
Ram:  4GB
Linux Mint 18:
`Linux jimmy-virtual-machine 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

---

Suave on Kestrel

```
dotnet --version
1.0.0-preview2-003121
```

Using [wrk ](https://github.com/wg/wrk)

``` \
Running 30s test @ http://localhost:8080
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    16.59ms    7.20ms 245.64ms   69.86%
    Req/Sec     2.01k   277.36     3.44k    69.22%
  720127 requests in 30.04s, 111.94MB read
Requests/sec:  23971.56
Transfer/sec:      3.73MB
```

---

Suave on Mono

```
mono --version
Mono JIT compiler version 4.4.1 (Nightly 4.4.1.0/4747417 Wed Jun 22 11:14:49 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    TLS:           __thread
    SIGSEGV:       altstack
    Notifications: epoll
    Architecture:  amd64
    Disabled:      none
    Misc:          softdebug 
    LLVM:          supported, not enabled.
    GC:            sgen
```

Using [wrk ](https://github.com/wg/wrk)

```
Running 30s test @ http://localhost:8083
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    47.93ms   84.73ms   1.98s    97.65%
    Req/Sec   832.29    287.51     5.06k    86.12%
  291167 requests in 30.04s, 43.60MB read
  Socket errors: connect 0, read 0, write 0, timeout 54
Requests/sec:   9692.17
Transfer/sec:      1.45MB
```

---

Suave on CoreCLR

Using [wrk ](https://github.com/wg/wrk)

```
Running 30s test @ http://localhost:8081
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    40.57ms   83.33ms   1.98s    98.82%
    Req/Sec     0.99k   313.98     6.69k    94.00%
  345489 requests in 30.09s, 52.72MB read
  Socket errors: connect 0, read 0, write 0, timeout 40
Requests/sec:  11480.08
Transfer/sec:      1.75MB
```

---

Plain Kestrel

```
Running 30s test @ http://localhost:8085
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.70ms    2.30ms  33.70ms   81.38%
    Req/Sec     9.34k     2.38k   24.85k    61.33%
  3353638 requests in 30.09s, 438.16MB read
Requests/sec: 111464.90
Transfer/sec:     14.56MB
```

---

MVC on Kestrel

```
Running 30s test @ http://localhost:8086
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    22.13ms   49.46ms 474.22ms   94.27%
    Req/Sec     2.97k     1.02k   10.30k    82.25%
  1065773 requests in 30.10s, 181.94MB read
Requests/sec:  35408.92
Transfer/sec:      6.04MB
```

---

NancyFx [barneyrubble](https://www.nuget.org/packages/Nancy/2.0.0-barneyrubble) on Kestrel

```
Running 30s test @ http://localhost:8087
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    26.98ms   18.37ms   1.60s    85.36%
    Req/Sec     1.23k   391.51     3.94k    86.02%
  441952 requests in 30.10s, 76.29MB read
  Socket errors: connect 0, read 0, write 0, timeout 9
Requests/sec:  14685.08
Transfer/sec:      2.53MB
```

**Comment by forki** [comment]
Can you please describe the test results in words?

**Comment by TheAngryByrd** [comment]
So I tried using an "Async all the things" Middleware 

```
type SuaveMiddlewareAllAsync (next : RequestDelegate, endpoint : Suave.Http.WebPart) =
    let invoke (ctx : HttpContext) = async {
        let! res = ctx |> toSuaveContext |> endpoint
        let ctx', body  =
            match res with
            | None -> setSuaveResponse ctx Suave.Http.HttpResult.empty
            | Some r -> setSuaveResponse ctx r.response
        return! ctx'.Response.WriteAsync body |> Async.AwaitIAsyncResult |> Async.Ignore
    }

    member this.Invoke(ctx : HttpContext) =
        ctx |> invoke |> Async.StartAsTask
```

but got pretty bad results as compared to the [RunSync](https://github.com/Krzysztof-Cieslak/Suave.Kestrel/blob/master/src/Suave.Kestrel/Suave.Kestrel.fs#L58) version

```
Running 30s test @ http://localhost:5000
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    40.67ms    8.00ms 204.06ms   72.29%
    Req/Sec   813.04    125.91     3.96k    77.42%
  291630 requests in 30.07s, 45.33MB read
Requests/sec:   9696.92
Transfer/sec:      1.51MB

```

**Comment by Krzysztof-Cieslak** [comment]
We could also try to add suave on CoreCLR to the mix, actually Suave on CoreCLR vs Suave on Kestrel on CoreCLR would be most interesting, I think.

**Comment by TheAngryByrd** [comment]
@forki I believe this is the correct way to read it and hope this is what you were looking for:

I ran the basic test for wrk

```
wrk -t12 -c400 -d30s http://localhost:5000
```

This uses 12 threads, tries to keep open 400 connections at a time, and lasts for 30 seconds.

Suave on Kestrel
The average latency for a request was, 14ms and 88% of the requests fell within 1 standard deviation, meaning most requests were close to 14ms.  
The average requests per second was 2400 and 91% fell within 1 standard deviation. 

Compared to Suave on Mono, it's slower and with a wider distribution with 22.2ms/78% and 753/62% respectfully.

**Comment by TheAngryByrd** [comment]
Updated for Suave on CoreCLR

**Comment by Krzysztof-Cieslak** [comment]
Great, thanks a lot! :)

**Comment by jskulavik** [comment]
Wow guys, what an interesting idea.  Isn't the avenue to explore that by which Libuv is wrapped though?  I don't know enough to speak intelligently about Suave, but I know that the perf boils down to how Libuv is marshalled via the CLR (or CoreCLR).  Really I'd just hope that Suave could outperform Kestrel via more efficient use of the C bindings for Libuv.

**Comment by forki** [comment]
@TheAngryByrd thanks buddy. How does this relate to the kestrel benchmarks that the ASP.NET team publishes?

/cc @haf

**Comment by Krzysztof-Cieslak** [comment]
Absolute number in comparison to tests done by ASP.Net team doesn't matter - different environments, different machines etc. (Here is link to their methodology of benchmarking - https://github.com/aspnet/benchmarks#generating-load)

Same, those numbers don't tell anything about production throughput of Suave

But having comparison of suave-mono, suave-coreClr and suave-kestrel on same environment can give some rough overview on relative speed of those solutions.

**Comment by forki** [comment]
@Krzysztof-Cieslak good point. I was just hoping to get a feeling if we are on the right track here.

**Comment by Krzysztof-Cieslak** [comment]
We should nicely ask ASP.Net team to lend us their test servers for a moment ;)

**Comment by TheAngryByrd** [comment]
@Krzysztof-Cieslak would it make sense to add the projects I created for benchmarks to samples and submit a PR?

**Comment by forki** [comment]
yes please

**Comment by toburger** [comment]
Also a perf comparison between kestrel barebone and kestrel with suave middleware would be cool to get numbers about the overhead added by suave.

**Comment by Krzysztof-Cieslak** [comment]
Yes, adding benchmark for Kestrel and Kestrel + normal ASP.Net controller would be interesting too.

**Comment by haf** [comment]
Hi guys! This is an interesting development.

First of all; keep on hacking and don't let anyone tell you what you can or cannot do creatively.

Secondly, I'm curious whether @TheAngryByrd has actually hit the performance ceiling of Suave, standing on its own?

Thirdly, my own priority, should I need less overhead per web request, would be to start profiling Suave rather than using Kestrel. I know some people find performance analysis frightening, or at least rather hard, but since Suave hasn't been optimised to any extent, there are likely many low hanging fruits.

Remember point 1 though ;)

**Comment by TheAngryByrd** [comment]
I'm away from my computer for a few days so it won't be until next week before I can add more.

**Comment by TheAngryByrd** [comment]
Updated with Plain Kestrel, MVC on Kestrel, and NancyFx on Kestrel. 

Also updated all the results from my last run.

**Comment by davidfowl** [comment]
Interesting numbers 😄

**Comment by imetallica** [comment]
Such a shame mono is so slow compared with the others.

**Comment by jchannon** [comment]
What version of Nancy?

**Comment by kolektiv** [comment]
This is very cool! The numbers might not be totally reliable, but the comparisons etc. are still informative. Is the source for the benchmarks available? I'm presuming this all has a requirement for the server framework to run on netcore, but I'd love to look at seeing how Freya compared when I get there.

**Comment by Krzysztof-Cieslak** [comment]
@jchannon: https://github.com/Krzysztof-Cieslak/Suave.Kestrel/blob/master/benchmark/NancyOnKestrel/project.json

All tested examples are in `benchmark` folder (Suave on Kestrel is in `samples` folder), so you can check if everything is OK.

**Comment by kolektiv** [comment]
Well, I think I might make a start on netcore compat for Freya and associated libraries tonight then - it's beginning to look useful!

**Comment by jchannon** [comment]
Looks Nancy needs to remove the Owin bridge and have Kestrel pipe straight to a NancyContext although not sure Kestrel can do that currently as it's tied to aspnet hosting?

**Comment by Krzysztof-Cieslak** [comment]
@jchannon: For Suave bridge I'm directly mapping Kestrel / aspnet HttpContext into SuaveHttpContext, run it through Suave pipeline, and at the end set response in Kestrel / aspnet HttpContext based on final state of SuaveHttpContext. I'd assume that something similar should be possible for Nancy too... but I know absolutely nothing about Nancy ;)

**Comment by jchannon** [comment]
Thats pretty much what the Owin bridge does. Ideally Kestrel should be
agnostic so it can pipe a request into Http/Nancy/Suave context rather than
needing a bridge

**Comment by kolektiv** [comment]
You're always going to need some kind of adaptation layer provided by the framework though? Which is, of course, the point of OWIN... Otherwise you end up tied to a single type model. Otherwise - what is it that Kestrel would pipe to Nancy/Suave/etc. without imposing a concrete dependency Suave -> Kestrel, or similar?

**Comment by TheAngryByrd** [comment]
@kolektiv Yeah these numbers are purely localhost on a gimped VM off my Macbook.  Definitely would like to see someone else release their benchmarks.  Maybe even setup something on some cloud provider (Digital ocean/AWS/Azure)?

@jchannon This particular test I was using [barneyrubble](https://www.nuget.org/packages/Nancy/2.0.0-barneyrubble), I'll update the top with that info.

**Comment by enricosada** [comment]
@TheAngryByrd just to be sure (i know it's stupid, but readme doesnt have it and asking is faster). `dotnet build` and `dotnet run` are with `-c Release` right?

A note:
if you want to run on windows using `ab` (apache benchmark), you need to add the `-k` argument.

**Comment by TheAngryByrd** [comment]
@enricosada no, I was just doing `dotnet run`.  I'll try that out later tonight.

**Comment by enricosada** [comment]
@TheAngryByrd always pass `-c Release` to both. Or just call `dotnet run -c Release` instead of both.

That's because if `dotnet run` doesnt find the output or source are not up-to-date with output, will redo the `dotnet build`  (so `dotnet run` will call `dotnet build`, the Debug conf).

As note, also project reference are checked on build, so `dotnet run .\samples\SimpleSample` will build `src\Suave.Kestrel` if needed

Well anyway suave.kestrel is not too big, so conf `Release` should not change results a lot i think, but dunno

**Comment by TheAngryByrd** [comment]
@enricosada so I did it over lunch.  Using release did improve them slightly but nothing significant, like a few hundred a second or so.

**Comment by enricosada** [comment]
Yes, with an helloworld doesnt matter much i think. Thx for trying @TheAngryByrd :smile:

**Comment by mvkara** [comment]
Nice numbers. Most benchmarks with Mono seem to use llvm so would be curious to see whether this makes any difference in your scenario. I've seen some improvements in our own benchmarking with this.

**Comment by TheAngryByrd** [comment]
@mvkra  I've never really used the LLVM features.  How easy is it to get that up and running?

**Comment by mvkara** [comment]
We just followed the guide at http://www.mono-project.com/docs/advanced/mono-llvm/ which was pretty straightforward. Not sure if following the first step is enough if you already have Mono installed or not. The reason I ask is we saw some reasonable performance improvements for some of our scenarios and it might close the gap a little between the net core and Mono numbers if that's the bottleneck here.

**Comment by TheAngryByrd** [comment]
I created a separate project to track performance benchmarks https://github.com/TheAngryByrd/dotnet-web-benchmarks

**Comment by mvkara** [comment]
For anyone whos still interested answered my own question (thanks for the testing code - made it easy) and did a comparison of the LLVM and non LLVM options to see how it compares with CoreCLR. See a ~25% speedup in performance compared to standard Mono with Suave so its not all IO that's causing the slowdown. On a side note CoreCLR with Suave fared worse on my machine than both Mono options (see https://github.com/TheAngryByrd/dotnet-web-benchmarks/pull/1 for a comparison with CoreCLR).

Maybe then it seems like much more speedup can be achieved by switching the transport over to Kestrel no matter which CLR you are using if that's possible? I'm guessing there's potential performance improvements that can be made at the transport layer of the Suave code.

SuaveOnMono with LLVM

```
Running 10s test @ http://127.0.0.1:8083/
  8 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    53.26ms   18.03ms 220.04ms   63.01%
    Req/Sec   627.28    439.13     2.56k    54.49%
  18833 requests in 10.10s, 2.98MB read
Requests/sec:   1865.44
Transfer/sec:    302.72KB
------------------------------
{"max":220045,"mean":53264.741942335,"min":2383,"stdev":18031.40932913}
{"bytes":3129573,"duration":10095731,"errors":{"connect":0,"read":0,"status":0,"timeout":0,"write":0},"requests":18833}
```

Suave On Mono

```
Running 10s test @ http://127.0.0.1:8083/
  8 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    68.08ms   19.89ms 339.64ms   72.66%
    Req/Sec   491.90    310.84     1.97k    50.33%
  14801 requests in 10.09s, 2.35MB read
Requests/sec:   1466.17
Transfer/sec:    238.44KB
------------------------------
{"max":339643,"mean":68083.438821701,"min":2981,"stdev":19890.446044108}
{"bytes":2464784,"duration":10094999,"errors":{"connect":0,"read":0,"status":0,"timeout":0,"write":0},"requests":14801}
```
