### ISSUE TITLE
Running sample fails with permission exception

### ISSUE THREAD

**Issue by forki** [Krzysztof-Cieslak/Suave.Kestrel#6]
![image](https://cloud.githubusercontent.com/assets/57396/16948727/a132daf6-4db6-11e6-93ec-826e72036177.png)

Ideas?

**Comment by Krzysztof-Cieslak** [comment]
You have something running on same port?

**Comment by forki** [comment]
which port and where can I influence that?

**Comment by forki** [comment]
found it. thanks
